package EditorWithSpellChecker;

import java.util.Timer;

public class Splash extends javax.swing.JDialog {
    
    public Splash(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }
    
    private void setTimer() {
        java.util.Timer theTimer = new Timer();
        theTimer.schedule(new DisposeTask(this), 2000);
    }
    
    private class DisposeTask extends java.util.TimerTask {
        
        private Splash splash;
        
        public DisposeTask(Splash splash) {
            this.splash = splash;
        }

        @Override
        public void run() {
            splash.dispose();
        }
        
    }
    
    @Override
    public void setVisible(boolean b) {
        setTimer();
        super.setVisible(b);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new java.awt.GridLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/metusoft.png"))); // NOI18N
        getContentPane().add(jLabel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
